name: Deploy react app
on:
 push: 
   branches:
     - master
     jobs:
 deploy:
  name: deploy app
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node-version: [ "12.x" ]
    steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1 
    with:
      node-version: ${{matrix.node-version}}
      - name: install packages
  run: npm install
  - name: deploy the app
  run: npm run deploy
  env:
   MDR_GH_PAGES: ${{ secrets.MDR_GH_PAGES }}